name: Deploy Telegram Bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          git config --global --add safe.directory /opt/telegrambot
          if [ ! -d /opt/telegrambot/.git ]; then
          git clone https://github.com/DrugsReminderAI/TelegramBot.git /opt/telegrambot
          fi
          cd /opt/telegrambot
          git pull origin main
          docker-compose build
          docker-compose up -d
          EOF
